# version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: travelsdb
      MYSQL_USER: onflyuser
      MYSQL_PASSWORD: onflyuserdb
      MYSQL_ROOT_PASSWORD: root
    
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: laravel-app
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    ports:
      - "8000:8000"
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
    depends_on:
      - mysql
    environment:
      - APP_URL=http://0.0.0.0:8000
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=travelsdb 
      - DB_USERNAME=onflyuser
      - DB_PASSWORD=onflyuserdb
      - SESSION_DOMAIN=localhost
      - SANCTUM_STATEFUL_DOMAINS=localhost:5173


  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000/api
    container_name: vue-app 
    ports:
      - "5173:80"
    depends_on:
      - backend

  
  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  db-data: